
module.exports.MENU_FILTERS = [
  "pizza",
  "burger",
  "juices",
  "non-veg-starters",
  "veg-starters",
  "curries",
  "fried-rice",
  "biryani",
  "non-veg-curries",
  "fast-food",
  "butter-milk",
  "dates-juices",
  "dry-fruit-juices",
  "egg",
  "french-fries",
  "dum-biryani",
  "chicken-mandi",
  "mutton-mandi",
  "fish",
  "dry-items",
  "roti-items",
  "veg-curries",
  "nonveg-curries",
];
